name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci || true

      - name: Run update script
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: node .github/scripts/update-waka.js

      - name: Commit README changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-action"
          git add README.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update waka README" || true
            git push
          else
            echo "No changes to commit"
          fi

    
